export interface SoundtrackTrack {
  id: string;
  title: string;
  volume: number;
  src: string;
  seconds: number;
}

export const SOUNDTRACK: readonly SoundtrackTrack[] = [
  { id: "v1-adrenaline-protocol", title: "Adrenaline Protocol", volume: 1, src: "/music/v1-adrenaline-protocol.mp3", seconds: 64.0 },
  { id: "v1-bassline-boost", title: "Bassline Boost", volume: 1, src: "/music/v1-bassline-boost.mp3", seconds: 64.0 },
  { id: "v1-boss-level", title: "Boss Level", volume: 1, src: "/music/v1-boss-level.mp3", seconds: 64.0 },
  { id: "v1-circuit-breaker", title: "Circuit Breaker", volume: 1, src: "/music/v1-circuit-breaker.mp3", seconds: 41.32 },
  { id: "v1-countdown-voltage", title: "Countdown Voltage", volume: 1, src: "/music/v1-countdown-voltage.mp3", seconds: 64.0 },
  { id: "v1-full-send", title: "Full Send", volume: 1, src: "/music/v1-full-send.mp3", seconds: 64.0 },
  { id: "v1-go-time", title: "Go Time", volume: 1, src: "/music/v1-go-time.mp3", seconds: 64.0 },
  { id: "v1-hat-roll-riot", title: "Hat Roll Riot", volume: 1, src: "/music/v1-hat-roll-riot.mp3", seconds: 64.0 },
  { id: "v1-heavy-rotation", title: "Heavy Rotation", volume: 1, src: "/music/v1-heavy-rotation.mp3", seconds: 64.0 },
  { id: "v1-hype-engine", title: "Hype Engine", volume: 1, src: "/music/v1-hype-engine.mp3", seconds: 64.0 },
  { id: "v1-ignition", title: "Ignition", volume: 1, src: "/music/v1-ignition.mp3", seconds: 64.0 },
  { id: "v1-late-night-grind", title: "Late Night Grind", volume: 1, src: "/music/v1-late-night-grind.mp3", seconds: 64.0 },
  { id: "v1-launch-sequence", title: "Launch Sequence", volume: 1, src: "/music/v1-launch-sequence.mp3", seconds: 64.0 },
  { id: "v1-neo-soul-underscore-for", title: "Neo Soul Underscore For", volume: 1, src: "/music/v1-neo-soul-underscore-for.mp3", seconds: 64.0 },
  { id: "v1-neon-overdrive", title: "Neon Overdrive", volume: 1, src: "/music/v1-neon-overdrive.mp3", seconds: 64.0 },
  { id: "v1-peak-hour", title: "Peak Hour", volume: 1, src: "/music/v1-peak-hour.mp3", seconds: 64.0 },
  { id: "v1-signal-boost", title: "Signal Boost", volume: 1, src: "/music/v1-signal-boost.mp3", seconds: 64.0 },
  { id: "v1-stream-start-surge", title: "Stream Start Surge", volume: 1, src: "/music/v1-stream-start-surge.mp3", seconds: 64.0 },
  { id: "v1-stream-start-surge-b", title: "Stream Start Surge", volume: 1, src: "/music/v1-stream-start-surge-b.mp3", seconds: 64.0 },
  { id: "v1-sub-rumble", title: "Sub Rumble", volume: 1, src: "/music/v1-sub-rumble.mp3", seconds: 64.0 },
  { id: "v1-turbo-mode", title: "Turbo Mode", volume: 1, src: "/music/v1-turbo-mode.mp3", seconds: 64.0 },
  { id: "v1-warhorn-trap", title: "Warhorn Trap", volume: 1, src: "/music/v1-warhorn-trap.mp3", seconds: 64.0 },
  { id: "v1-warm-lo-fi-hip", title: "Warm Lo Fi Hip", volume: 1, src: "/music/v1-warm-lo-fi-hip.mp3", seconds: 64.0 },
  { id: "v2-rapid-cycle", title: "Rapid Cycle", volume: 2, src: "/music/v2-rapid-cycle.mp3", seconds: 64.0 },
  { id: "v2-blue-hour", title: "Blue Hour", volume: 2, src: "/music/v2-blue-hour.mp3", seconds: 64.0 },
  { id: "v2-pixel-riot", title: "Pixel Riot", volume: 2, src: "/music/v2-pixel-riot.mp3", seconds: 64.0 },
  { id: "v2-guaracha-heat", title: "Guaracha Heat", volume: 2, src: "/music/v2-guaracha-heat.mp3", seconds: 64.0 },
  { id: "v2-aurora-mode", title: "Aurora Mode", volume: 2, src: "/music/v2-aurora-mode.mp3", seconds: 64.0 },
  { id: "v2-ship-it", title: "Ship It", volume: 2, src: "/music/v2-ship-it.mp3", seconds: 64.0 },
  { id: "v2-neon-bazaar", title: "Neon Bazaar", volume: 2, src: "/music/v2-neon-bazaar.mp3", seconds: 64.0 },
  { id: "v2-static-garden", title: "Static Garden", volume: 2, src: "/music/v2-static-garden.mp3", seconds: 64.0 },
  { id: "v2-overclock", title: "Overclock", volume: 2, src: "/music/v2-overclock.mp3", seconds: 64.0 },
  { id: "v2-signal-flare", title: "Signal Flare", volume: 2, src: "/music/v2-signal-flare.mp3", seconds: 64.0 },
  { id: "v2-sunburst-ave", title: "Sunburst Ave", volume: 2, src: "/music/v2-sunburst-ave.mp3", seconds: 64.0 },
  { id: "v2-hard-reset", title: "Hard Reset", volume: 2, src: "/music/v2-hard-reset.mp3", seconds: 64.0 },
  { id: "v2-ember-rise", title: "Ember Rise", volume: 2, src: "/music/v2-ember-rise.mp3", seconds: 64.0 },
  { id: "v2-chrome-coast", title: "Chrome Coast", volume: 2, src: "/music/v2-chrome-coast.mp3", seconds: 64.0 },
  { id: "v2-pressure-wave", title: "Pressure Wave", volume: 2, src: "/music/v2-pressure-wave.mp3", seconds: 64.0 },
  { id: "v2-long-runway", title: "Long Runway", volume: 2, src: "/music/v2-long-runway.mp3", seconds: 64.0 },
  { id: "v2-kawaii-circuit", title: "Kawaii Circuit", volume: 2, src: "/music/v2-kawaii-circuit.mp3", seconds: 64.0 },
  { id: "v2-acid-rally", title: "Acid Rally", volume: 2, src: "/music/v2-acid-rally.mp3", seconds: 64.0 },
  { id: "v2-solar-panels", title: "Solar Panels", volume: 2, src: "/music/v2-solar-panels.mp3", seconds: 64.0 },
  { id: "v2-neon-pulse", title: "Neon Pulse", volume: 2, src: "/music/v2-neon-pulse.mp3", seconds: 64.0 },
  { id: "v2-copper-wire", title: "Copper Wire", volume: 2, src: "/music/v2-copper-wire.mp3", seconds: 64.0 },
  { id: "v2-amber-signal", title: "Amber Signal", volume: 2, src: "/music/v2-amber-signal.mp3", seconds: 64.0 },
  { id: "v3-bounce-protocol", title: "Bounce Protocol", volume: 3, src: "/music/v3-bounce-protocol.mp3", seconds: 64.0 },
  { id: "v3-first-light", title: "First Light", volume: 3, src: "/music/v3-first-light.mp3", seconds: 64.0 },
  { id: "v3-zero-latency", title: "Zero Latency", volume: 3, src: "/music/v3-zero-latency.mp3", seconds: 64.0 },
  { id: "v3-turbo-lane", title: "Turbo Lane", volume: 3, src: "/music/v3-turbo-lane.mp3", seconds: 64.0 },
  { id: "v3-ion-drift", title: "Ion Drift", volume: 3, src: "/music/v3-ion-drift.mp3", seconds: 64.0 },
  { id: "v3-payday", title: "Payday", volume: 3, src: "/music/v3-payday.mp3", seconds: 64.0 },
  { id: "v3-iron-bloom", title: "Iron Bloom", volume: 3, src: "/music/v3-iron-bloom.mp3", seconds: 64.0 },
  { id: "v3-split-second", title: "Split Second", volume: 3, src: "/music/v3-split-second.mp3", seconds: 64.0 },
  { id: "v3-solar-flare-drive", title: "Solar Flare Drive", volume: 3, src: "/music/v3-solar-flare-drive.mp3", seconds: 64.0 },
  { id: "v3-green-candles", title: "Green Candles", volume: 3, src: "/music/v3-green-candles.mp3", seconds: 64.0 },
  { id: "v3-slipstream", title: "Slipstream", volume: 3, src: "/music/v3-slipstream.mp3", seconds: 64.0 },
  { id: "v3-autopilot", title: "Autopilot", volume: 3, src: "/music/v3-autopilot.mp3", seconds: 64.0 },
  { id: "v3-voltage-drop", title: "Voltage Drop", volume: 3, src: "/music/v3-voltage-drop.mp3", seconds: 64.0 },
  { id: "v3-perimeter", title: "Perimeter", volume: 3, src: "/music/v3-perimeter.mp3", seconds: 64.0 },
  { id: "v3-nitro-bloom", title: "Nitro Bloom", volume: 3, src: "/music/v3-nitro-bloom.mp3", seconds: 64.0 },
  { id: "v3-neon-commute", title: "Neon Commute", volume: 3, src: "/music/v3-neon-commute.mp3", seconds: 64.0 },
  { id: "v3-brass-tacks", title: "Brass Tacks", volume: 3, src: "/music/v3-brass-tacks.mp3", seconds: 64.0 },
  { id: "v3-skyline-sprint", title: "Skyline Sprint", volume: 3, src: "/music/v3-skyline-sprint.mp3", seconds: 64.0 },
  { id: "v3-chrome-temple", title: "Chrome Temple", volume: 3, src: "/music/v3-chrome-temple.mp3", seconds: 64.0 },
  { id: "v3-afterburner", title: "Afterburner", volume: 3, src: "/music/v3-afterburner.mp3", seconds: 64.0 },
  { id: "v3-overtime", title: "Overtime", volume: 3, src: "/music/v3-overtime.mp3", seconds: 64.0 },
  { id: "v3-sunrise-protocol", title: "Sunrise Protocol", volume: 3, src: "/music/v3-sunrise-protocol.mp3", seconds: 64.0 },
];
